# Generated by Django 4.1 on 2022-08-08 07:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testo',
            name='area',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
